### ISSUE TITLE
404 & 304 errors 

### ISSUE THREAD

**Issue by hesamnobari** [AVGP/cloud9hub#29]
`a@a-virtual-machine:~/cloud9hub$ sudo node server.js -p 8080 -l 0.0.0.0 -a :
Express server listening on port 3105
GET / 302 3ms - 56b
GET /login 304 32ms
GET /lib/fontawesome/css/font-awesome.min.css 304 9ms
GET /lib/flat-ui-official/bootstrap/css/bootstrap.css 304 9ms
GET /lib/flat-ui-official/css/flat-ui.css 304 9ms
GET /css/style.css 404 9ms
GET /lib/flat-ui-official/js/jquery-1.8.3.min.js 304 9ms
GET /lib/flat-ui-official/js/jquery-ui-1.10.3.custom.min.js 304 8ms
GET /lib/flat-ui-official/js/jquery.ui.touch-punch.min.js 304 1ms
GET /lib/flat-ui-official/js/bootstrap.min.js 304 2ms
GET /lib/flat-ui-official/js/bootstrap-select.js 304 2ms
GET /lib/flat-ui-official/js/bootstrap-switch.js 304 2ms
GET /lib/flat-ui-official/js/flatui-checkbox.js 304 3ms
GET /lib/flat-ui-official/js/flatui-radio.js 304 2ms
GET /lib/flat-ui-official/js/jquery.tagsinput.js 304 1ms
GET /lib/flat-ui-official/js/jquery.placeholder.js 304 2ms
GET /lib/flat-ui-official/js/jquery.stacktable.js 404 1ms
GET /lib/angular/angular.min.js 304 1ms
GET /lib/angular-route/angular-route.min.js 304 1ms
GET /js/workspace/workspaceController.js 304 2ms
GET /js/workspace/workspaceModule.js 304 2ms
GET /js/app.js 304 2ms
GET /lib/flat-ui-official/fonts/lato/lato-bold.woff 304 1ms
GET /lib/fontawesome/fonts/fontawesome-webfont.woff?v=4.0.3 304 1ms
GET /lib/flat-ui-official/fonts/lato/lato-regular.woff 304 2ms
GET /auth/github 302 3ms - 378b
GET /auth/github/callback?code=02239fceb4fcf8ce8da7 302 2096ms - 68b
GET / 200 4ms - 1.71kb
GET /lib/fontawesome/css/font-awesome.min.css 304 8ms
GET /lib/flat-ui-official/bootstrap/css/bootstrap.css 304 6ms
GET /lib/flat-ui-official/css/flat-ui.css 304 6ms
GET /css/style.css 404 6ms
GET /lib/flat-ui-official/js/jquery-1.8.3.min.js 304 5ms
GET /lib/flat-ui-official/js/jquery-ui-1.10.3.custom.min.js 304 5ms
GET /lib/flat-ui-official/js/jquery.ui.touch-punch.min.js 304 3ms
GET /lib/flat-ui-official/js/bootstrap-select.js 304 2ms
GET /lib/flat-ui-official/js/bootstrap.min.js 304 1ms
GET /lib/flat-ui-official/js/bootstrap-switch.js 304 3ms
GET /lib/flat-ui-official/js/flatui-checkbox.js 304 2ms
GET /lib/flat-ui-official/js/flatui-radio.js 304 1ms
GET /lib/flat-ui-official/js/jquery.tagsinput.js 304 1ms
GET /lib/flat-ui-official/js/jquery.placeholder.js 304 1ms
GET /lib/flat-ui-official/js/jquery.stacktable.js 404 0ms
GET /lib/angular/angular.min.js 304 3ms
GET /lib/angular-route/angular-route.min.js 304 2ms
GET /js/workspace/workspaceController.js 304 2ms
GET /js/workspace/workspaceModule.js 304 1ms
GET /js/app.js 304 2ms
GET /lib/flat-ui-official/fonts/lato/lato-regular.woff 304 1ms
GET /partials/workspace.html 304 1ms
GET /workspace 200 4ms - 97b
GET /lib/flat-ui-official/fonts/lato/lato-bold.woff 304 2ms
setting nextFreeWorkspacePort to 5001
checking if port 5001 is taken
port 5001 seems to be available
Starting /home/a/cloud9hub/controllers/../../c9/bin/cloud9.sh for workspace Amirreza on port 5001
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn /home/a/cloud9hub/controllers/../../c9/bin/cloud9.sh ENOENT
    at exports._errnoException (util.js:870:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:441:9)
    at process._tickCallback (node.js:355:17)
`
I think cloud9hub cannot connect to cloud9
we have access to dashboard but not workspace..

**Comment by Harjot1Singh** [comment]
Which branch did you use?
